"""Скрипт заполнения БД марками и моделями автомобилей.

Запуск внутри контейнера:
    docker exec autohub_api python /app/app/seed_vehicles.py
"""

import asyncio
import os

from sqlalchemy import select, func
from sqlalchemy.ext.asyncio import AsyncSession, async_sessionmaker, create_async_engine

DATABASE_URL = os.environ.get(
    "DATABASE_URL",
    "postgresql+asyncpg://autohub:devpassword@postgres:5432/autohub_db",
)

engine = create_async_engine(DATABASE_URL, echo=False)
SessionFactory = async_sessionmaker(engine, class_=AsyncSession, expire_on_commit=False)

# ---------------------------------------------------------------------------
# Данные: {brand_name: (name_en, country, [модели...])}
# Модель: (name, body_type, year_from, year_to)  — year_to=None означает текущий выпуск
# ---------------------------------------------------------------------------

BRANDS_DATA = {
    # ── КИТАЙСКИЕ МАРКИ ─────────────────────────────────────────────────────
    "Haval": ("Haval", "Китай", [
        ("H6", "suv", 2011, None),
        ("H9", "suv", 2014, None),
        ("H2", "suv", 2014, None),
        ("H2S", "suv", 2017, None),
        ("F7", "suv", 2018, None),
        ("F7x", "suv", 2019, None),
        ("Jolion", "suv", 2020, None),
        ("Dargo", "suv", 2021, None),
        ("H5", "suv", 2010, None),
        ("M6", "suv", 2018, None),
        ("Big Dog", "suv", 2020, None),
    ]),
    "Geely": ("Geely", "Китай", [
        ("Atlas", "suv", 2016, None),
        ("Atlas Pro", "suv", 2021, None),
        ("Coolray", "suv", 2019, None),
        ("Emgrand", "sedan", 2009, None),
        ("Emgrand X7", "suv", 2011, None),
        ("Tugella", "suv", 2019, None),
        ("Monjaro", "suv", 2022, None),
        ("Okavango", "suv", 2020, None),
        ("Преmium", "sedan", 2016, None),
        ("Cityray", "suv", 2022, None),
        ("Galaxy L7", "suv", 2023, None),
    ]),
    "Chery": ("Chery", "Китай", [
        ("Tiggo 4", "suv", 2017, None),
        ("Tiggo 4 Pro", "suv", 2021, None),
        ("Tiggo 7 Pro", "suv", 2020, None),
        ("Tiggo 7 Pro Max", "suv", 2022, None),
        ("Tiggo 8", "suv", 2018, None),
        ("Tiggo 8 Pro", "suv", 2020, None),
        ("Tiggo 8 Pro Max", "suv", 2022, None),
        ("Arrizo 5", "sedan", 2015, None),
        ("Arrizo 5 Plus", "sedan", 2021, None),
        ("Arrizo 8", "sedan", 2022, None),
        ("Tiggo 2", "suv", 2016, None),
        ("Tiggo 3", "suv", 2014, None),
        ("Amulet", "sedan", 2003, 2012),
    ]),
    "EXEED": ("EXEED", "Китай", [
        ("TXL", "suv", 2019, None),
        ("VX", "suv", 2020, None),
        ("LX", "suv", 2022, None),
        ("RX", "suv", 2023, None),
        ("EX", "suv", 2021, None),
    ]),
    "Omoda": ("Omoda", "Китай", [
        ("C5", "suv", 2022, None),
        ("S5", "sedan", 2022, None),
        ("C5 EV", "suv", 2023, None),
    ]),
    "Jetour": ("Jetour", "Китай", [
        ("X70", "suv", 2018, None),
        ("X70 Plus", "suv", 2020, None),
        ("X90", "suv", 2019, None),
        ("X90 Plus", "suv", 2021, None),
        ("Dashing", "suv", 2022, None),
        ("T2", "suv", 2023, None),
    ]),
    "BYD": ("BYD", "Китай", [
        ("Han", "sedan", 2020, None),
        ("Tang", "suv", 2015, None),
        ("Song Plus", "suv", 2020, None),
        ("Song Pro", "suv", 2019, None),
        ("Atto 3", "suv", 2021, None),
        ("Seal", "sedan", 2022, None),
        ("Dolphin", "hatchback", 2021, None),
        ("Yuan Plus", "suv", 2021, None),
        ("F3", "sedan", 2005, None),
        ("Qin Plus", "sedan", 2021, None),
    ]),
    "Changan": ("Changan", "Китай", [
        ("CS35 Plus", "suv", 2018, None),
        ("CS55 Plus", "suv", 2017, None),
        ("CS75 Plus", "suv", 2014, None),
        ("CS85", "suv", 2019, None),
        ("CS95", "suv", 2017, None),
        ("Uni-T", "suv", 2020, None),
        ("Uni-K", "suv", 2021, None),
        ("Uni-V", "sedan", 2022, None),
        ("Lamore", "sedan", 2022, None),
        ("Alsvin", "sedan", 2020, None),
        ("CS15", "suv", 2016, None),
    ]),
    "JAC": ("JAC", "Китай", [
        ("S3", "suv", 2014, None),
        ("S4", "suv", 2018, None),
        ("S7", "suv", 2017, None),
        ("JS4", "suv", 2021, None),
        ("JS6", "suv", 2022, None),
        ("J7", "sedan", 2019, None),
        ("T8", "pickup", 2018, None),
        ("iEV7", "hatchback", 2017, None),
        ("E10X", "hatchback", 2021, None),
    ]),
    "BAIC": ("BAIC", "Китай", [
        ("X55", "suv", 2018, None),
        ("X75", "suv", 2016, None),
        ("BJ40", "suv", 2013, None),
        ("BJ80", "suv", 2016, None),
        ("D50", "sedan", 2017, None),
        ("EU5", "sedan", 2018, None),
        ("EX5", "suv", 2018, None),
        ("BJ60", "suv", 2021, None),
    ]),
    "Dongfeng": ("Dongfeng", "Китай", [
        ("AX4", "suv", 2017, None),
        ("AX7", "suv", 2015, None),
        ("AX7 Pro", "suv", 2021, None),
        ("T5", "suv", 2017, None),
        ("T5 Evo", "suv", 2020, None),
        ("E70", "sedan", 2019, None),
        ("Forthing T5L", "suv", 2020, None),
    ]),
    "GAC": ("GAC", "Китай", [
        ("GS3", "suv", 2017, None),
        ("GS4", "suv", 2015, None),
        ("GS5", "suv", 2019, None),
        ("GS7", "suv", 2016, None),
        ("GS8", "suv", 2016, None),
        ("Aion S", "sedan", 2019, None),
        ("Aion V", "suv", 2020, None),
        ("GS4 Plus", "suv", 2021, None),
    ]),
    "Great Wall": ("Great Wall", "Китай", [
        ("Hover H3", "suv", 2005, 2016),
        ("Hover H5", "suv", 2010, 2018),
        ("Hover H6", "suv", 2011, 2017),
        ("Poer", "pickup", 2019, None),
    ]),
    "MG": ("MG", "Китай", [
        ("ZS", "suv", 2017, None),
        ("ZS EV", "suv", 2019, None),
        ("HS", "suv", 2018, None),
        ("RX5", "suv", 2016, None),
        ("5", "sedan", 2020, None),
        ("6", "sedan", 2010, None),
        ("Marvel R", "suv", 2020, None),
        ("3", "hatchback", 2012, None),
        ("4", "hatchback", 2021, None),
        ("Cyberster", "convertible", 2023, None),
    ]),
    "Roewe": ("Roewe", "Китай", [
        ("RX5", "suv", 2016, None),
        ("RX5 Plus", "suv", 2020, None),
        ("i5", "sedan", 2018, None),
        ("i6", "sedan", 2019, None),
        ("RX8", "suv", 2018, None),
        ("D7", "sedan", 2022, None),
    ]),
    "FAW": ("FAW", "Китай", [
        ("Besturn X40", "suv", 2017, None),
        ("Besturn X80", "suv", 2018, None),
        ("Besturn B50", "sedan", 2009, None),
        ("Besturn B70", "sedan", 2006, None),
        ("Oley", "sedan", 2012, 2020),
        ("Xenia EV", "suv", 2020, None),
    ]),
    "Bestune": ("Bestune", "Китай", [
        ("T77", "suv", 2018, None),
        ("T77 Pro", "suv", 2020, None),
        ("T99", "suv", 2019, None),
        ("T55", "suv", 2021, None),
        ("NA", "sedan", 2020, None),
    ]),
    "Lixiang": ("Li Auto", "Китай", [
        ("L6", "suv", 2024, None),
        ("L7", "suv", 2023, None),
        ("L8", "suv", 2022, None),
        ("L9", "suv", 2022, None),
        ("One", "suv", 2019, 2022),
    ]),
    "NIO": ("NIO", "Китай", [
        ("ET5", "sedan", 2022, None),
        ("ET7", "sedan", 2022, None),
        ("ES6", "suv", 2019, None),
        ("ES7", "suv", 2022, None),
        ("ES8", "suv", 2018, None),
        ("EC6", "coupe_suv", 2020, None),
        ("EC7", "coupe_suv", 2023, None),
    ]),
    "AITO": ("AITO", "Китай", [
        ("M5", "suv", 2022, None),
        ("M7", "suv", 2022, None),
        ("M9", "suv", 2024, None),
    ]),

    # ── ЯПОНСКИЕ МАРКИ ──────────────────────────────────────────────────────
    "Toyota": ("Toyota", "Япония", [
        ("Camry", "sedan", 1982, None),
        ("Corolla", "sedan", 1966, None),
        ("RAV4", "suv", 1994, None),
        ("Land Cruiser", "suv", 1951, None),
        ("Land Cruiser Prado", "suv", 1984, None),
        ("Hilux", "pickup", 1968, None),
        ("Highlander", "suv", 2000, None),
        ("Fortuner", "suv", 2004, None),
        ("Venza", "suv", 2008, None),
        ("Crown", "sedan", 1955, None),
        ("Yaris", "hatchback", 1999, None),
        ("C-HR", "suv", 2016, None),
        ("bZ4X", "suv", 2022, None),
        ("Prius", "sedan", 1997, None),
        ("Rush", "suv", 2006, None),
    ]),
    "Lexus": ("Lexus", "Япония", [
        ("LX", "suv", 1996, None),
        ("GX", "suv", 2003, None),
        ("RX", "suv", 1997, None),
        ("NX", "suv", 2014, None),
        ("ES", "sedan", 1989, None),
        ("LS", "sedan", 1989, None),
        ("IS", "sedan", 1999, None),
        ("UX", "suv", 2018, None),
        ("RZ", "suv", 2023, None),
        ("LM", "minivan", 2019, None),
    ]),
    "Honda": ("Honda", "Япония", [
        ("CR-V", "suv", 1995, None),
        ("Civic", "sedan", 1972, None),
        ("Accord", "sedan", 1976, None),
        ("Pilot", "suv", 2002, None),
        ("HR-V", "suv", 2015, None),
        ("Jazz", "hatchback", 2001, None),
        ("Fit", "hatchback", 2001, None),
        ("Odyssey", "minivan", 1994, None),
        ("ZR-V", "suv", 2022, None),
    ]),
    "Nissan": ("Nissan", "Япония", [
        ("X-Trail", "suv", 2000, None),
        ("Qashqai", "suv", 2006, None),
        ("Pathfinder", "suv", 1985, None),
        ("Patrol", "suv", 1951, None),
        ("Murano", "suv", 2002, None),
        ("Teana", "sedan", 2003, None),
        ("Juke", "suv", 2010, None),
        ("Navara", "pickup", 1985, None),
        ("Leaf", "hatchback", 2010, None),
        ("Kicks", "suv", 2016, None),
        ("Almera", "sedan", 1995, None),
        ("Note", "hatchback", 2004, None),
        ("Serena", "minivan", 1991, None),
    ]),
    "Mazda": ("Mazda", "Япония", [
        ("CX-5", "suv", 2011, None),
        ("CX-9", "suv", 2006, None),
        ("CX-3", "suv", 2015, None),
        ("CX-30", "suv", 2019, None),
        ("CX-60", "suv", 2022, None),
        ("Mazda 3", "sedan", 2003, None),
        ("Mazda 6", "sedan", 2002, None),
        ("Mazda 2", "hatchback", 2007, None),
        ("MX-5", "convertible", 1989, None),
    ]),
    "Mitsubishi": ("Mitsubishi", "Япония", [
        ("Outlander", "suv", 2001, None),
        ("Pajero", "suv", 1981, None),
        ("Pajero Sport", "suv", 1996, None),
        ("ASX", "suv", 2010, None),
        ("Eclipse Cross", "suv", 2017, None),
        ("L200", "pickup", 1978, None),
        ("Lancer", "sedan", 1973, 2017),
        ("Galant", "sedan", 1969, 2012),
        ("Colt", "hatchback", 2002, 2012),
        ("Xpander", "minivan", 2017, None),
    ]),
    "Subaru": ("Subaru", "Япония", [
        ("Forester", "suv", 1997, None),
        ("Outback", "suv", 1994, None),
        ("XV", "suv", 2011, None),
        ("Impreza", "sedan", 1992, None),
        ("Legacy", "sedan", 1989, None),
        ("WRX", "sedan", 2014, None),
        ("Crosstrek", "suv", 2012, None),
        ("Ascent", "suv", 2018, None),
        ("BRZ", "coupe", 2012, None),
        ("Solterra", "suv", 2022, None),
    ]),
    "Suzuki": ("Suzuki", "Япония", [
        ("Vitara", "suv", 1988, None),
        ("Grand Vitara", "suv", 1997, None),
        ("Jimny", "suv", 1970, None),
        ("Swift", "hatchback", 2004, None),
        ("SX4", "suv", 2006, None),
        ("S-Cross", "suv", 2013, None),
    ]),
    "Infiniti": ("Infiniti", "Япония", [
        ("QX80", "suv", 2010, None),
        ("QX60", "suv", 2012, None),
        ("QX56", "suv", 2003, None),
        ("QX50", "suv", 2007, None),
        ("Q50", "sedan", 2013, None),
        ("Q60", "coupe", 2008, None),
        ("FX35", "suv", 2003, 2013),
        ("FX50", "suv", 2008, 2013),
        ("QX70", "suv", 2008, 2017),
        ("EX25", "suv", 2007, 2013),
        ("G35", "sedan", 2002, 2013),
    ]),

    # ── КОРЕЙСКИЕ МАРКИ ──────────────────────────────────────────────────────
    "Hyundai": ("Hyundai", "Южная Корея", [
        ("Tucson", "suv", 2004, None),
        ("Santa Fe", "suv", 2000, None),
        ("Creta", "suv", 2015, None),
        ("Sonata", "sedan", 1985, None),
        ("Elantra", "sedan", 1990, None),
        ("Accent", "sedan", 1994, None),
        ("i30", "hatchback", 2007, None),
        ("Solaris", "sedan", 2010, None),
        ("ix35", "suv", 2009, None),
        ("Palisade", "suv", 2018, None),
        ("Ioniq 5", "suv", 2021, None),
        ("Ioniq 6", "sedan", 2022, None),
        ("NEXO", "suv", 2018, None),
        ("Kona", "suv", 2017, None),
        ("Venue", "suv", 2019, None),
        ("Starex", "minivan", 1997, None),
        ("H-1", "minivan", 1997, None),
        ("Staria", "minivan", 2021, None),
    ]),
    "Kia": ("Kia", "Южная Корея", [
        ("Sportage", "suv", 1993, None),
        ("Sorento", "suv", 2002, None),
        ("Carnival", "minivan", 1998, None),
        ("K5", "sedan", 2010, None),
        ("K8", "sedan", 2021, None),
        ("Optima", "sedan", 2000, None),
        ("Cerato", "sedan", 2003, None),
        ("Rio", "sedan", 2000, None),
        ("Seltos", "suv", 2019, None),
        ("Telluride", "suv", 2019, None),
        ("Stinger", "sedan", 2017, None),
        ("EV6", "suv", 2021, None),
        ("EV9", "suv", 2023, None),
        ("Mohave", "suv", 2008, None),
        ("Ceed", "hatchback", 2006, None),
        ("Stonic", "suv", 2017, None),
        ("Niro", "hatchback", 2016, None),
    ]),
    "Genesis": ("Genesis", "Южная Корея", [
        ("G80", "sedan", 2016, None),
        ("G90", "sedan", 2016, None),
        ("G70", "sedan", 2017, None),
        ("GV80", "suv", 2020, None),
        ("GV70", "suv", 2021, None),
        ("GV60", "suv", 2022, None),
        ("G80 EV", "sedan", 2021, None),
    ]),
    "SsangYong": ("SsangYong", "Южная Корея", [
        ("Rexton", "suv", 2001, None),
        ("Actyon", "suv", 2005, None),
        ("Tivoli", "suv", 2015, None),
        ("Korando", "suv", 1983, None),
        ("Musso", "pickup", 2018, None),
        ("Torres", "suv", 2022, None),
    ]),

    # ── НЕМЕЦКИЕ МАРКИ ──────────────────────────────────────────────────────
    "Volkswagen": ("Volkswagen", "Германия", [
        ("Tiguan", "suv", 2007, None),
        ("Touareg", "suv", 2002, None),
        ("Polo", "sedan", 1975, None),
        ("Passat", "sedan", 1973, None),
        ("Jetta", "sedan", 1979, None),
        ("Golf", "hatchback", 1974, None),
        ("Touran", "minivan", 2003, None),
        ("Teramont", "suv", 2016, None),
        ("Taos", "suv", 2020, None),
        ("Multivan", "minivan", 1990, None),
        ("Atlas", "suv", 2016, None),
        ("ID.4", "suv", 2020, None),
        ("ID.6", "suv", 2021, None),
        ("Phaeton", "sedan", 2002, 2016),
    ]),
    "BMW": ("BMW", "Германия", [
        ("X1", "suv", 2009, None),
        ("X3", "suv", 2003, None),
        ("X5", "suv", 1999, None),
        ("X6", "suv", 2008, None),
        ("X7", "suv", 2018, None),
        ("3 Series", "sedan", 1975, None),
        ("5 Series", "sedan", 1972, None),
        ("7 Series", "sedan", 1977, None),
        ("1 Series", "hatchback", 2004, None),
        ("2 Series", "coupe", 2013, None),
        ("4 Series", "coupe", 2013, None),
        ("6 Series", "coupe", 2003, None),
        ("8 Series", "coupe", 2018, None),
        ("iX", "suv", 2021, None),
        ("iX3", "suv", 2020, None),
        ("i4", "sedan", 2021, None),
        ("i7", "sedan", 2022, None),
        ("M3", "sedan", 1986, None),
        ("M5", "sedan", 1985, None),
        ("X2", "suv", 2018, None),
        ("X4", "suv", 2014, None),
    ]),
    "Mercedes-Benz": ("Mercedes-Benz", "Германия", [
        ("GLE", "suv", 2015, None),
        ("GLC", "suv", 2015, None),
        ("GLS", "suv", 2006, None),
        ("GLB", "suv", 2019, None),
        ("GLA", "suv", 2013, None),
        ("E-Class", "sedan", 1984, None),
        ("C-Class", "sedan", 1982, None),
        ("S-Class", "sedan", 1972, None),
        ("A-Class", "hatchback", 1997, None),
        ("B-Class", "hatchback", 2005, None),
        ("CLA", "sedan", 2013, None),
        ("CLS", "sedan", 2004, None),
        ("G-Class", "suv", 1979, None),
        ("EQC", "suv", 2019, None),
        ("EQE", "sedan", 2021, None),
        ("EQS", "sedan", 2021, None),
        ("V-Class", "minivan", 1996, None),
        ("Sprinter", "van", 1995, None),
        ("AMG GT", "coupe", 2014, None),
    ]),
    "Audi": ("Audi", "Германия", [
        ("Q3", "suv", 2011, None),
        ("Q5", "suv", 2008, None),
        ("Q7", "suv", 2005, None),
        ("Q8", "suv", 2018, None),
        ("A3", "sedan", 1996, None),
        ("A4", "sedan", 1994, None),
        ("A6", "sedan", 1994, None),
        ("A7", "sedan", 2010, None),
        ("A8", "sedan", 1994, None),
        ("e-tron", "suv", 2019, None),
        ("Q4 e-tron", "suv", 2021, None),
        ("RS6", "universal", 2002, None),
        ("S6", "sedan", 1999, None),
        ("TT", "coupe", 1998, None),
        ("R8", "coupe", 2006, None),
        ("Q2", "suv", 2016, None),
    ]),
    "Porsche": ("Porsche", "Германия", [
        ("Cayenne", "suv", 2002, None),
        ("Macan", "suv", 2014, None),
        ("Panamera", "sedan", 2009, None),
        ("Taycan", "sedan", 2019, None),
        ("911", "coupe", 1963, None),
        ("Boxster", "convertible", 1996, None),
        ("Cayman", "coupe", 2005, None),
    ]),
    "Skoda": ("Skoda", "Чехия", [
        ("Octavia", "sedan", 1996, None),
        ("Superb", "sedan", 2001, None),
        ("Kodiaq", "suv", 2016, None),
        ("Karoq", "suv", 2017, None),
        ("Fabia", "hatchback", 1999, None),
        ("Rapid", "sedan", 2012, None),
        ("Scala", "hatchback", 2019, None),
        ("Enyaq iV", "suv", 2020, None),
        ("Kamiq", "suv", 2019, None),
    ]),

    # ── ФРАНЦУЗСКИЕ МАРКИ ────────────────────────────────────────────────────
    "Renault": ("Renault", "Франция", [
        ("Duster", "suv", 2010, None),
        ("Kaptur", "suv", 2016, None),
        ("Logan", "sedan", 2004, None),
        ("Sandero", "hatchback", 2008, None),
        ("Megane", "hatchback", 1995, None),
        ("Fluence", "sedan", 2009, 2017),
        ("Koleos", "suv", 2007, None),
        ("Arkana", "suv", 2019, None),
        ("Scenic", "minivan", 1996, None),
        ("Laguna", "sedan", 1993, 2015),
        ("Trafic", "van", 1981, None),
    ]),
    "Peugeot": ("Peugeot", "Франция", [
        ("2008", "suv", 2013, None),
        ("3008", "suv", 2017, None),
        ("5008", "minivan", 2009, None),
        ("408", "sedan", 2010, None),
        ("308", "hatchback", 2007, None),
        ("508", "sedan", 2011, None),
        ("4008", "suv", 2012, None),
        ("e-2008", "suv", 2020, None),
        ("e-208", "hatchback", 2019, None),
    ]),

    # ── АМЕРИКАНСКИЕ МАРКИ ───────────────────────────────────────────────────
    "Chevrolet": ("Chevrolet", "США", [
        ("Tahoe", "suv", 1995, None),
        ("Suburban", "suv", 1934, None),
        ("Traverse", "suv", 2008, None),
        ("Equinox", "suv", 2004, None),
        ("Trailblazer", "suv", 2001, None),
        ("Colorado", "pickup", 2004, None),
        ("Captiva", "suv", 2006, None),
        ("Cruze", "sedan", 2008, None),
        ("Malibu", "sedan", 1964, None),
        ("Niva", "suv", 2002, None),
        ("Blazer", "suv", 2018, None),
        ("Silverado", "pickup", 1998, None),
        ("Impala", "sedan", 1958, 2020),
    ]),
    "Ford": ("Ford", "США", [
        ("Explorer", "suv", 1990, None),
        ("Expedition", "suv", 1997, None),
        ("F-150", "pickup", 1975, None),
        ("Ranger", "pickup", 1983, None),
        ("Focus", "hatchback", 1998, None),
        ("Mondeo", "sedan", 1992, None),
        ("Kuga", "suv", 2008, None),
        ("Escape", "suv", 2000, None),
        ("Edge", "suv", 2006, None),
        ("Mustang", "coupe", 1964, None),
        ("Mustang Mach-E", "suv", 2020, None),
        ("EcoSport", "suv", 2013, None),
        ("Everest", "suv", 2003, None),
    ]),
    "Jeep": ("Jeep", "США", [
        ("Grand Cherokee", "suv", 1992, None),
        ("Wrangler", "suv", 1986, None),
        ("Compass", "suv", 2006, None),
        ("Renegade", "suv", 2014, None),
        ("Cherokee", "suv", 1974, None),
        ("Gladiator", "pickup", 2019, None),
        ("Avenger", "suv", 2023, None),
    ]),
    "Cadillac": ("Cadillac", "США", [
        ("Escalade", "suv", 1999, None),
        ("XT5", "suv", 2016, None),
        ("XT6", "suv", 2019, None),
        ("CT5", "sedan", 2019, None),
        ("CT6", "sedan", 2015, None),
        ("ATS", "sedan", 2012, None),
        ("CTS", "sedan", 2002, None),
        ("LYRIQ", "suv", 2023, None),
    ]),
    "Lincoln": ("Lincoln", "США", [
        ("Navigator", "suv", 1997, None),
        ("Aviator", "suv", 2019, None),
        ("Continental", "sedan", 2017, None),
        ("MKX", "suv", 2006, None),
        ("MKZ", "sedan", 2006, None),
        ("Corsair", "suv", 2019, None),
    ]),

    # ── БРИТАНСКИЕ МАРКИ ─────────────────────────────────────────────────────
    "Land Rover": ("Land Rover", "Великобритания", [
        ("Range Rover", "suv", 1970, None),
        ("Range Rover Sport", "suv", 2005, None),
        ("Range Rover Evoque", "suv", 2011, None),
        ("Range Rover Velar", "suv", 2017, None),
        ("Discovery", "suv", 1989, None),
        ("Discovery Sport", "suv", 2014, None),
        ("Defender", "suv", 1983, None),
        ("Freelander", "suv", 1997, 2014),
    ]),
    "Jaguar": ("Jaguar", "Великобритания", [
        ("XE", "sedan", 2015, None),
        ("XF", "sedan", 2007, None),
        ("XJ", "sedan", 1968, None),
        ("F-Pace", "suv", 2016, None),
        ("E-Pace", "suv", 2017, None),
        ("I-Pace", "suv", 2018, None),
        ("F-Type", "coupe", 2013, None),
    ]),

    # ── ШВЕДСКИЕ МАРКИ ───────────────────────────────────────────────────────
    "Volvo": ("Volvo", "Швеция", [
        ("XC90", "suv", 2002, None),
        ("XC60", "suv", 2008, None),
        ("XC40", "suv", 2017, None),
        ("S60", "sedan", 2000, None),
        ("S90", "sedan", 2016, None),
        ("V60", "universal", 2010, None),
        ("V90", "universal", 2016, None),
        ("C40", "suv", 2021, None),
        ("EX90", "suv", 2024, None),
    ]),

    # ── ИТАЛЬЯНСКИЕ МАРКИ ────────────────────────────────────────────────────
    "Fiat": ("Fiat", "Италия", [
        ("500", "hatchback", 2007, None),
        ("Panda", "hatchback", 1980, None),
        ("Tipo", "sedan", 1988, None),
        ("Doblo", "minivan", 2000, None),
        ("Ducato", "van", 1981, None),
        ("Fullback", "pickup", 2016, None),
    ]),

    # ── РОССИЙСКИЕ МАРКИ ─────────────────────────────────────────────────────
    "Lada": ("Lada", "Россия", [
        ("Granta", "sedan", 2011, None),
        ("Vesta", "sedan", 2015, None),
        ("X-Ray", "hatchback", 2015, None),
        ("Niva Legend", "suv", 1977, None),
        ("Niva Travel", "suv", 2021, None),
        ("Largus", "universal", 2012, None),
        ("Vesta Sport", "sedan", 2018, None),
        ("Granta Sport", "sedan", 2020, None),
        ("2107", "sedan", 1982, 2014),
        ("2106", "sedan", 1975, 2006),
        ("2109", "hatchback", 1987, 2011),
        ("Samara", "hatchback", 1984, 2013),
        ("Priora", "sedan", 2007, 2018),
        ("Kalina", "hatchback", 2004, 2018),
        ("4x4", "suv", 1977, None),
    ]),
    "УАЗ": ("UAZ", "Россия", [
        ("Patriot", "suv", 2005, None),
        ("Hunter", "suv", 2003, None),
        ("Pickup", "pickup", 2008, None),
        ("Буханка", "van", 1965, None),
        ("Профи", "pickup", 2017, None),
    ]),
    "ГАЗ": ("GAZ", "Россия", [
        ("Газель Next", "van", 2013, None),
        ("Газель Business", "van", 2010, None),
        ("Соболь NN", "van", 2021, None),
    ]),
}


async def seed_vehicles() -> None:
    from app.models.vehicle import CarBrand, CarModel

    async with SessionFactory() as session:
        # Проверяем — уже есть данные?
        count_result = await session.execute(
            select(func.count()).select_from(CarBrand)
        )
        count = count_result.scalar_one()
        if count > 0:
            print(f"[seed_vehicles] car_brands уже содержит {count} записей. Пропускаем.")
            return

        total_brands = 0
        total_models = 0

        for brand_name, (name_en, country, models) in BRANDS_DATA.items():
            brand = CarBrand(
                name=brand_name,
                name_en=name_en,
                country=country,
                is_active=True,
            )
            session.add(brand)
            await session.flush()  # получаем brand.id

            for model_tuple in models:
                name, body_type, year_from, year_to = model_tuple
                model = CarModel(
                    brand_id=brand.id,
                    name=name,
                    body_type=body_type,
                    year_from=year_from,
                    year_to=year_to,
                    is_active=True,
                )
                session.add(model)
                total_models += 1

            total_brands += 1
            print(f"[seed_vehicles] + {brand_name} ({country}) — {len(models)} моделей")

        await session.commit()
        print(f"\n[seed_vehicles] Готово! Марок: {total_brands}, Моделей: {total_models}")


if __name__ == "__main__":
    asyncio.run(seed_vehicles())
